# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import crawler_pb2 as crawler__full__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crawler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddLinks = channel.unary_unary(
                '/crawler.AdminService/AddLinks',
                request_serializer=crawler__full__pb2.AddLinksRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.AddLinksResponse.FromString,
                _registered_method=True)
        self.ExtractLinks = channel.unary_unary(
                '/crawler.AdminService/ExtractLinks',
                request_serializer=crawler__full__pb2.ExtractLinksRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.ExtractLinksResponse.FromString,
                _registered_method=True)
        self.CrawlSinglePage = channel.unary_unary(
                '/crawler.AdminService/CrawlSinglePage',
                request_serializer=crawler__full__pb2.CrawlSinglePageRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.CrawlSinglePageResponse.FromString,
                _registered_method=True)
        self.GetLinksStatus = channel.unary_unary(
                '/crawler.AdminService/GetLinksStatus',
                request_serializer=crawler__full__pb2.Empty.SerializeToString,
                response_deserializer=crawler__full__pb2.LinksStatusResponse.FromString,
                _registered_method=True)
        self.GetLinksStatusByDomain = channel.unary_unary(
                '/crawler.AdminService/GetLinksStatusByDomain',
                request_serializer=crawler__full__pb2.Empty.SerializeToString,
                response_deserializer=crawler__full__pb2.LinksByDomainResponse.FromString,
                _registered_method=True)
        self.ListLinks = channel.unary_unary(
                '/crawler.AdminService/ListLinks',
                request_serializer=crawler__full__pb2.ListLinksRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.ListLinksResponse.FromString,
                _registered_method=True)
        self.DeleteLink = channel.unary_unary(
                '/crawler.AdminService/DeleteLink',
                request_serializer=crawler__full__pb2.DeleteLinkRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.ListPages = channel.unary_unary(
                '/crawler.AdminService/ListPages',
                request_serializer=crawler__full__pb2.ListPagesRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.ListPagesResponse.FromString,
                _registered_method=True)
        self.ListPagesByDomain = channel.unary_unary(
                '/crawler.AdminService/ListPagesByDomain',
                request_serializer=crawler__full__pb2.ListPagesByDomainRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.ListPagesResponse.FromString,
                _registered_method=True)
        self.GetPage = channel.unary_unary(
                '/crawler.AdminService/GetPage',
                request_serializer=crawler__full__pb2.GetPageRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.PageDetailResponse.FromString,
                _registered_method=True)
        self.GetDomainStats = channel.unary_unary(
                '/crawler.AdminService/GetDomainStats',
                request_serializer=crawler__full__pb2.DomainRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.DomainStatsResponse.FromString,
                _registered_method=True)
        self.DeleteDomain = channel.unary_unary(
                '/crawler.AdminService/DeleteDomain',
                request_serializer=crawler__full__pb2.DomainRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.DeleteDomainResponse.FromString,
                _registered_method=True)
        self.TriggerCrawl = channel.unary_unary(
                '/crawler.AdminService/TriggerCrawl',
                request_serializer=crawler__full__pb2.TriggerCrawlRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.CrawlResponse.FromString,
                _registered_method=True)
        self.RescanAll = channel.unary_unary(
                '/crawler.AdminService/RescanAll',
                request_serializer=crawler__full__pb2.TriggerCrawlRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.CrawlResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrawlSinglePage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinksStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinksStatusByDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPagesByDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDomainStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerCrawl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RescanAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLinks,
                    request_deserializer=crawler__full__pb2.AddLinksRequest.FromString,
                    response_serializer=crawler__full__pb2.AddLinksResponse.SerializeToString,
            ),
            'ExtractLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractLinks,
                    request_deserializer=crawler__full__pb2.ExtractLinksRequest.FromString,
                    response_serializer=crawler__full__pb2.ExtractLinksResponse.SerializeToString,
            ),
            'CrawlSinglePage': grpc.unary_unary_rpc_method_handler(
                    servicer.CrawlSinglePage,
                    request_deserializer=crawler__full__pb2.CrawlSinglePageRequest.FromString,
                    response_serializer=crawler__full__pb2.CrawlSinglePageResponse.SerializeToString,
            ),
            'GetLinksStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinksStatus,
                    request_deserializer=crawler__full__pb2.Empty.FromString,
                    response_serializer=crawler__full__pb2.LinksStatusResponse.SerializeToString,
            ),
            'GetLinksStatusByDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLinksStatusByDomain,
                    request_deserializer=crawler__full__pb2.Empty.FromString,
                    response_serializer=crawler__full__pb2.LinksByDomainResponse.SerializeToString,
            ),
            'ListLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLinks,
                    request_deserializer=crawler__full__pb2.ListLinksRequest.FromString,
                    response_serializer=crawler__full__pb2.ListLinksResponse.SerializeToString,
            ),
            'DeleteLink': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLink,
                    request_deserializer=crawler__full__pb2.DeleteLinkRequest.FromString,
                    response_serializer=crawler__full__pb2.OperationResponse.SerializeToString,
            ),
            'ListPages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPages,
                    request_deserializer=crawler__full__pb2.ListPagesRequest.FromString,
                    response_serializer=crawler__full__pb2.ListPagesResponse.SerializeToString,
            ),
            'ListPagesByDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPagesByDomain,
                    request_deserializer=crawler__full__pb2.ListPagesByDomainRequest.FromString,
                    response_serializer=crawler__full__pb2.ListPagesResponse.SerializeToString,
            ),
            'GetPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPage,
                    request_deserializer=crawler__full__pb2.GetPageRequest.FromString,
                    response_serializer=crawler__full__pb2.PageDetailResponse.SerializeToString,
            ),
            'GetDomainStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomainStats,
                    request_deserializer=crawler__full__pb2.DomainRequest.FromString,
                    response_serializer=crawler__full__pb2.DomainStatsResponse.SerializeToString,
            ),
            'DeleteDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDomain,
                    request_deserializer=crawler__full__pb2.DomainRequest.FromString,
                    response_serializer=crawler__full__pb2.DeleteDomainResponse.SerializeToString,
            ),
            'TriggerCrawl': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerCrawl,
                    request_deserializer=crawler__full__pb2.TriggerCrawlRequest.FromString,
                    response_serializer=crawler__full__pb2.CrawlResponse.SerializeToString,
            ),
            'RescanAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RescanAll,
                    request_deserializer=crawler__full__pb2.TriggerCrawlRequest.FromString,
                    response_serializer=crawler__full__pb2.CrawlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crawler.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crawler.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/AddLinks',
            crawler__full__pb2.AddLinksRequest.SerializeToString,
            crawler__full__pb2.AddLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/ExtractLinks',
            crawler__full__pb2.ExtractLinksRequest.SerializeToString,
            crawler__full__pb2.ExtractLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrawlSinglePage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/CrawlSinglePage',
            crawler__full__pb2.CrawlSinglePageRequest.SerializeToString,
            crawler__full__pb2.CrawlSinglePageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinksStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/GetLinksStatus',
            crawler__full__pb2.Empty.SerializeToString,
            crawler__full__pb2.LinksStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinksStatusByDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/GetLinksStatusByDomain',
            crawler__full__pb2.Empty.SerializeToString,
            crawler__full__pb2.LinksByDomainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/ListLinks',
            crawler__full__pb2.ListLinksRequest.SerializeToString,
            crawler__full__pb2.ListLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/DeleteLink',
            crawler__full__pb2.DeleteLinkRequest.SerializeToString,
            crawler__full__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/ListPages',
            crawler__full__pb2.ListPagesRequest.SerializeToString,
            crawler__full__pb2.ListPagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPagesByDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/ListPagesByDomain',
            crawler__full__pb2.ListPagesByDomainRequest.SerializeToString,
            crawler__full__pb2.ListPagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/GetPage',
            crawler__full__pb2.GetPageRequest.SerializeToString,
            crawler__full__pb2.PageDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDomainStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/GetDomainStats',
            crawler__full__pb2.DomainRequest.SerializeToString,
            crawler__full__pb2.DomainStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/DeleteDomain',
            crawler__full__pb2.DomainRequest.SerializeToString,
            crawler__full__pb2.DeleteDomainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerCrawl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/TriggerCrawl',
            crawler__full__pb2.TriggerCrawlRequest.SerializeToString,
            crawler__full__pb2.CrawlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RescanAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.AdminService/RescanAll',
            crawler__full__pb2.TriggerCrawlRequest.SerializeToString,
            crawler__full__pb2.CrawlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/crawler.SearchService/Search',
                request_serializer=crawler__full__pb2.SearchRequest.SerializeToString,
                response_deserializer=crawler__full__pb2.SearchResponse.FromString,
                _registered_method=True)


class SearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=crawler__full__pb2.SearchRequest.FromString,
                    response_serializer=crawler__full__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crawler.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crawler.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.SearchService/Search',
            crawler__full__pb2.SearchRequest.SerializeToString,
            crawler__full__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
