// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: proto/crawler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_AddLinks_FullMethodName               = "/crawler.AdminService/AddLinks"
	AdminService_ExtractLinks_FullMethodName           = "/crawler.AdminService/ExtractLinks"
	AdminService_CrawlSinglePage_FullMethodName        = "/crawler.AdminService/CrawlSinglePage"
	AdminService_GetLinksStatus_FullMethodName         = "/crawler.AdminService/GetLinksStatus"
	AdminService_GetLinksStatusByDomain_FullMethodName = "/crawler.AdminService/GetLinksStatusByDomain"
	AdminService_ListLinks_FullMethodName              = "/crawler.AdminService/ListLinks"
	AdminService_DeleteLink_FullMethodName             = "/crawler.AdminService/DeleteLink"
	AdminService_ListPages_FullMethodName              = "/crawler.AdminService/ListPages"
	AdminService_ListPagesByDomain_FullMethodName      = "/crawler.AdminService/ListPagesByDomain"
	AdminService_GetPage_FullMethodName                = "/crawler.AdminService/GetPage"
	AdminService_GetDomainStats_FullMethodName         = "/crawler.AdminService/GetDomainStats"
	AdminService_DeleteDomain_FullMethodName           = "/crawler.AdminService/DeleteDomain"
	AdminService_TriggerCrawl_FullMethodName           = "/crawler.AdminService/TriggerCrawl"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	AddLinks(ctx context.Context, in *AddLinksRequest, opts ...grpc.CallOption) (*AddLinksResponse, error)
	ExtractLinks(ctx context.Context, in *ExtractLinksRequest, opts ...grpc.CallOption) (*ExtractLinksResponse, error)
	CrawlSinglePage(ctx context.Context, in *CrawlSinglePageRequest, opts ...grpc.CallOption) (*CrawlSinglePageResponse, error)
	GetLinksStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LinksStatusResponse, error)
	GetLinksStatusByDomain(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LinksByDomainResponse, error)
	ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error)
	DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error)
	ListPagesByDomain(ctx context.Context, in *ListPagesByDomainRequest, opts ...grpc.CallOption) (*ListPagesResponse, error)
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*PageDetailResponse, error)
	GetDomainStats(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainStatsResponse, error)
	DeleteDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DeleteDomainResponse, error)
	TriggerCrawl(ctx context.Context, in *TriggerCrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) AddLinks(ctx context.Context, in *AddLinksRequest, opts ...grpc.CallOption) (*AddLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLinksResponse)
	err := c.cc.Invoke(ctx, AdminService_AddLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ExtractLinks(ctx context.Context, in *ExtractLinksRequest, opts ...grpc.CallOption) (*ExtractLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractLinksResponse)
	err := c.cc.Invoke(ctx, AdminService_ExtractLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CrawlSinglePage(ctx context.Context, in *CrawlSinglePageRequest, opts ...grpc.CallOption) (*CrawlSinglePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlSinglePageResponse)
	err := c.cc.Invoke(ctx, AdminService_CrawlSinglePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLinksStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LinksStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinksStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetLinksStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLinksStatusByDomain(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LinksByDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinksByDomainResponse)
	err := c.cc.Invoke(ctx, AdminService_GetLinksStatusByDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksResponse)
	err := c.cc.Invoke(ctx, AdminService_ListLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPagesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListPagesByDomain(ctx context.Context, in *ListPagesByDomainRequest, opts ...grpc.CallOption) (*ListPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPagesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListPagesByDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*PageDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageDetailResponse)
	err := c.cc.Invoke(ctx, AdminService_GetPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDomainStats(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDomainStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DeleteDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDomainResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TriggerCrawl(ctx context.Context, in *TriggerCrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, AdminService_TriggerCrawl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	AddLinks(context.Context, *AddLinksRequest) (*AddLinksResponse, error)
	ExtractLinks(context.Context, *ExtractLinksRequest) (*ExtractLinksResponse, error)
	CrawlSinglePage(context.Context, *CrawlSinglePageRequest) (*CrawlSinglePageResponse, error)
	GetLinksStatus(context.Context, *Empty) (*LinksStatusResponse, error)
	GetLinksStatusByDomain(context.Context, *Empty) (*LinksByDomainResponse, error)
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error)
	DeleteLink(context.Context, *DeleteLinkRequest) (*OperationResponse, error)
	ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error)
	ListPagesByDomain(context.Context, *ListPagesByDomainRequest) (*ListPagesResponse, error)
	GetPage(context.Context, *GetPageRequest) (*PageDetailResponse, error)
	GetDomainStats(context.Context, *DomainRequest) (*DomainStatsResponse, error)
	DeleteDomain(context.Context, *DomainRequest) (*DeleteDomainResponse, error)
	TriggerCrawl(context.Context, *TriggerCrawlRequest) (*CrawlResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) AddLinks(context.Context, *AddLinksRequest) (*AddLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLinks not implemented")
}
func (UnimplementedAdminServiceServer) ExtractLinks(context.Context, *ExtractLinksRequest) (*ExtractLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractLinks not implemented")
}
func (UnimplementedAdminServiceServer) CrawlSinglePage(context.Context, *CrawlSinglePageRequest) (*CrawlSinglePageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrawlSinglePage not implemented")
}
func (UnimplementedAdminServiceServer) GetLinksStatus(context.Context, *Empty) (*LinksStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinksStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetLinksStatusByDomain(context.Context, *Empty) (*LinksByDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinksStatusByDomain not implemented")
}
func (UnimplementedAdminServiceServer) ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLinks not implemented")
}
func (UnimplementedAdminServiceServer) DeleteLink(context.Context, *DeleteLinkRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLink not implemented")
}
func (UnimplementedAdminServiceServer) ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPages not implemented")
}
func (UnimplementedAdminServiceServer) ListPagesByDomain(context.Context, *ListPagesByDomainRequest) (*ListPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPagesByDomain not implemented")
}
func (UnimplementedAdminServiceServer) GetPage(context.Context, *GetPageRequest) (*PageDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedAdminServiceServer) GetDomainStats(context.Context, *DomainRequest) (*DomainStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainStats not implemented")
}
func (UnimplementedAdminServiceServer) DeleteDomain(context.Context, *DomainRequest) (*DeleteDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDomain not implemented")
}
func (UnimplementedAdminServiceServer) TriggerCrawl(context.Context, *TriggerCrawlRequest) (*CrawlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerCrawl not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_AddLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddLinks(ctx, req.(*AddLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ExtractLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ExtractLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ExtractLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ExtractLinks(ctx, req.(*ExtractLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CrawlSinglePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlSinglePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CrawlSinglePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CrawlSinglePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CrawlSinglePage(ctx, req.(*CrawlSinglePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLinksStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLinksStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLinksStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLinksStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLinksStatusByDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLinksStatusByDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLinksStatusByDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLinksStatusByDomain(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListLinks(ctx, req.(*ListLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteLink(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListPages(ctx, req.(*ListPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListPagesByDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPagesByDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListPagesByDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListPagesByDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListPagesByDomain(ctx, req.(*ListPagesByDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDomainStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDomainStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDomainStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDomainStats(ctx, req.(*DomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteDomain(ctx, req.(*DomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TriggerCrawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerCrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TriggerCrawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TriggerCrawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TriggerCrawl(ctx, req.(*TriggerCrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLinks",
			Handler:    _AdminService_AddLinks_Handler,
		},
		{
			MethodName: "ExtractLinks",
			Handler:    _AdminService_ExtractLinks_Handler,
		},
		{
			MethodName: "CrawlSinglePage",
			Handler:    _AdminService_CrawlSinglePage_Handler,
		},
		{
			MethodName: "GetLinksStatus",
			Handler:    _AdminService_GetLinksStatus_Handler,
		},
		{
			MethodName: "GetLinksStatusByDomain",
			Handler:    _AdminService_GetLinksStatusByDomain_Handler,
		},
		{
			MethodName: "ListLinks",
			Handler:    _AdminService_ListLinks_Handler,
		},
		{
			MethodName: "DeleteLink",
			Handler:    _AdminService_DeleteLink_Handler,
		},
		{
			MethodName: "ListPages",
			Handler:    _AdminService_ListPages_Handler,
		},
		{
			MethodName: "ListPagesByDomain",
			Handler:    _AdminService_ListPagesByDomain_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _AdminService_GetPage_Handler,
		},
		{
			MethodName: "GetDomainStats",
			Handler:    _AdminService_GetDomainStats_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _AdminService_DeleteDomain_Handler,
		},
		{
			MethodName: "TriggerCrawl",
			Handler:    _AdminService_TriggerCrawl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crawler.proto",
}

const (
	SearchService_Search_FullMethodName = "/crawler.SearchService/Search"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SearchService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crawler.proto",
}
