// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: crawler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{0}
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinksRequest) Reset() {
	*x = AddLinksRequest{}
	mi := &file_crawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinksRequest) ProtoMessage() {}

func (x *AddLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinksRequest.ProtoReflect.Descriptor instead.
func (*AddLinksRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{2}
}

func (x *AddLinksRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type AddLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int32                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Duplicated    int32                  `protobuf:"varint,2,opt,name=duplicated,proto3" json:"duplicated,omitempty"`
	Errors        int32                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinksResponse) Reset() {
	*x = AddLinksResponse{}
	mi := &file_crawler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinksResponse) ProtoMessage() {}

func (x *AddLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinksResponse.ProtoReflect.Descriptor instead.
func (*AddLinksResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{3}
}

func (x *AddLinksResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *AddLinksResponse) GetDuplicated() int32 {
	if x != nil {
		return x.Duplicated
	}
	return 0
}

func (x *AddLinksResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

type ExtractLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractLinksRequest) Reset() {
	*x = ExtractLinksRequest{}
	mi := &file_crawler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractLinksRequest) ProtoMessage() {}

func (x *ExtractLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractLinksRequest.ProtoReflect.Descriptor instead.
func (*ExtractLinksRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{4}
}

func (x *ExtractLinksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ExtractLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processed     int32                  `protobuf:"varint,1,opt,name=processed,proto3" json:"processed,omitempty"`
	LinksAdded    int32                  `protobuf:"varint,2,opt,name=links_added,json=linksAdded,proto3" json:"links_added,omitempty"`
	Errors        int32                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractLinksResponse) Reset() {
	*x = ExtractLinksResponse{}
	mi := &file_crawler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractLinksResponse) ProtoMessage() {}

func (x *ExtractLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractLinksResponse.ProtoReflect.Descriptor instead.
func (*ExtractLinksResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{5}
}

func (x *ExtractLinksResponse) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *ExtractLinksResponse) GetLinksAdded() int32 {
	if x != nil {
		return x.LinksAdded
	}
	return 0
}

func (x *ExtractLinksResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

type CrawlSinglePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlSinglePageRequest) Reset() {
	*x = CrawlSinglePageRequest{}
	mi := &file_crawler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlSinglePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlSinglePageRequest) ProtoMessage() {}

func (x *CrawlSinglePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlSinglePageRequest.ProtoReflect.Descriptor instead.
func (*CrawlSinglePageRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{6}
}

func (x *CrawlSinglePageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CrawlSinglePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlSinglePageResponse) Reset() {
	*x = CrawlSinglePageResponse{}
	mi := &file_crawler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlSinglePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlSinglePageResponse) ProtoMessage() {}

func (x *CrawlSinglePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlSinglePageResponse.ProtoReflect.Descriptor instead.
func (*CrawlSinglePageResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{7}
}

func (x *CrawlSinglePageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrawlSinglePageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CrawlSinglePageResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_crawler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LinkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkItem) Reset() {
	*x = LinkItem{}
	mi := &file_crawler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkItem) ProtoMessage() {}

func (x *LinkItem) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkItem.ProtoReflect.Descriptor instead.
func (*LinkItem) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{9}
}

func (x *LinkItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LinkItem) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *LinkItem) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LinkItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LinkItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *LinkItem) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	UrlFilter     string                 `protobuf:"bytes,4,opt,name=url_filter,json=urlFilter,proto3" json:"url_filter,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // filtro opcional: pending, success, error, blocked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_crawler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{10}
}

func (x *ListLinksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLinksRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListLinksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListLinksRequest) GetUrlFilter() string {
	if x != nil {
		return x.UrlFilter
	}
	return ""
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkItem            `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_crawler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{11}
}

func (x *ListLinksResponse) GetLinks() []*LinkItem {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LinksStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pending       int32                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Success       int32                  `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         int32                  `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	Blocked       int32                  `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinksStatusResponse) Reset() {
	*x = LinksStatusResponse{}
	mi := &file_crawler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinksStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksStatusResponse) ProtoMessage() {}

func (x *LinksStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksStatusResponse.ProtoReflect.Descriptor instead.
func (*LinksStatusResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{12}
}

func (x *LinksStatusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LinksStatusResponse) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *LinksStatusResponse) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *LinksStatusResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *LinksStatusResponse) GetBlocked() int32 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

type LinkDomainStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pending       int32                  `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	Success       int32                  `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         int32                  `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkDomainStat) Reset() {
	*x = LinkDomainStat{}
	mi := &file_crawler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkDomainStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkDomainStat) ProtoMessage() {}

func (x *LinkDomainStat) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkDomainStat.ProtoReflect.Descriptor instead.
func (*LinkDomainStat) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{13}
}

func (x *LinkDomainStat) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LinkDomainStat) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LinkDomainStat) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *LinkDomainStat) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *LinkDomainStat) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type LinksByDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*LinkDomainStat      `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinksByDomainResponse) Reset() {
	*x = LinksByDomainResponse{}
	mi := &file_crawler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinksByDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinksByDomainResponse) ProtoMessage() {}

func (x *LinksByDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinksByDomainResponse.ProtoReflect.Descriptor instead.
func (*LinksByDomainResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{14}
}

func (x *LinksByDomainResponse) GetDomains() []*LinkDomainStat {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ListPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesRequest) Reset() {
	*x = ListPagesRequest{}
	mi := &file_crawler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesRequest) ProtoMessage() {}

func (x *ListPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesRequest.ProtoReflect.Descriptor instead.
func (*ListPagesRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{15}
}

func (x *ListPagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPagesRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type ListPagesByDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesByDomainRequest) Reset() {
	*x = ListPagesByDomainRequest{}
	mi := &file_crawler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesByDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesByDomainRequest) ProtoMessage() {}

func (x *ListPagesByDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesByDomainRequest.ProtoReflect.Descriptor instead.
func (*ListPagesByDomainRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{16}
}

func (x *ListPagesByDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListPagesByDomainRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPagesByDomainRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type PageSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	WordCount     int32                  `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	CrawledAt     string                 `protobuf:"bytes,6,opt,name=crawled_at,json=crawledAt,proto3" json:"crawled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageSummary) Reset() {
	*x = PageSummary{}
	mi := &file_crawler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageSummary) ProtoMessage() {}

func (x *PageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageSummary.ProtoReflect.Descriptor instead.
func (*PageSummary) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{17}
}

func (x *PageSummary) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PageSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PageSummary) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PageSummary) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *PageSummary) GetCrawledAt() string {
	if x != nil {
		return x.CrawledAt
	}
	return ""
}

type ListPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*PageSummary         `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_crawler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{18}
}

func (x *ListPagesResponse) GetPages() []*PageSummary {
	if x != nil {
		return x.Pages
	}
	return nil
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_crawler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{19}
}

func (x *GetPageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PageDetailResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TextContent     string                 `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	Summary         string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	WordCount       int32                  `protobuf:"varint,6,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	Keywords        []string               `protobuf:"bytes,7,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Language        string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	StatusCode      int32                  `protobuf:"varint,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	CrawledAt       string                 `protobuf:"bytes,10,opt,name=crawled_at,json=crawledAt,proto3" json:"crawled_at,omitempty"`
	EmbeddingStatus string                 `protobuf:"bytes,11,opt,name=embedding_status,json=embeddingStatus,proto3" json:"embedding_status,omitempty"`
	ChunksCount     int32                  `protobuf:"varint,12,opt,name=chunks_count,json=chunksCount,proto3" json:"chunks_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageDetailResponse) Reset() {
	*x = PageDetailResponse{}
	mi := &file_crawler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageDetailResponse) ProtoMessage() {}

func (x *PageDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageDetailResponse.ProtoReflect.Descriptor instead.
func (*PageDetailResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{20}
}

func (x *PageDetailResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PageDetailResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageDetailResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PageDetailResponse) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *PageDetailResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PageDetailResponse) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *PageDetailResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *PageDetailResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *PageDetailResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PageDetailResponse) GetCrawledAt() string {
	if x != nil {
		return x.CrawledAt
	}
	return ""
}

func (x *PageDetailResponse) GetEmbeddingStatus() string {
	if x != nil {
		return x.EmbeddingStatus
	}
	return ""
}

func (x *PageDetailResponse) GetChunksCount() int32 {
	if x != nil {
		return x.ChunksCount
	}
	return 0
}

type DomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainRequest) Reset() {
	*x = DomainRequest{}
	mi := &file_crawler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainRequest) ProtoMessage() {}

func (x *DomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainRequest.ProtoReflect.Descriptor instead.
func (*DomainRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{21}
}

func (x *DomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type DomainStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Domain            string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	TotalLinks        int32                  `protobuf:"varint,2,opt,name=total_links,json=totalLinks,proto3" json:"total_links,omitempty"`
	TotalPagesCrawled int32                  `protobuf:"varint,3,opt,name=total_pages_crawled,json=totalPagesCrawled,proto3" json:"total_pages_crawled,omitempty"`
	Pending           int32                  `protobuf:"varint,4,opt,name=pending,proto3" json:"pending,omitempty"`
	Extracted         int32                  `protobuf:"varint,5,opt,name=extracted,proto3" json:"extracted,omitempty"`
	Success           int32                  `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Error             int32                  `protobuf:"varint,7,opt,name=error,proto3" json:"error,omitempty"`
	Blocked           int32                  `protobuf:"varint,8,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DomainStatsResponse) Reset() {
	*x = DomainStatsResponse{}
	mi := &file_crawler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainStatsResponse) ProtoMessage() {}

func (x *DomainStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainStatsResponse.ProtoReflect.Descriptor instead.
func (*DomainStatsResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{22}
}

func (x *DomainStatsResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainStatsResponse) GetTotalLinks() int32 {
	if x != nil {
		return x.TotalLinks
	}
	return 0
}

func (x *DomainStatsResponse) GetTotalPagesCrawled() int32 {
	if x != nil {
		return x.TotalPagesCrawled
	}
	return 0
}

func (x *DomainStatsResponse) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *DomainStatsResponse) GetExtracted() int32 {
	if x != nil {
		return x.Extracted
	}
	return 0
}

func (x *DomainStatsResponse) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *DomainStatsResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *DomainStatsResponse) GetBlocked() int32 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

type DeleteDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinksDeleted  int32                  `protobuf:"varint,1,opt,name=links_deleted,json=linksDeleted,proto3" json:"links_deleted,omitempty"`
	PagesDeleted  int32                  `protobuf:"varint,2,opt,name=pages_deleted,json=pagesDeleted,proto3" json:"pages_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainResponse) Reset() {
	*x = DeleteDomainResponse{}
	mi := &file_crawler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainResponse) ProtoMessage() {}

func (x *DeleteDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainResponse.ProtoReflect.Descriptor instead.
func (*DeleteDomainResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteDomainResponse) GetLinksDeleted() int32 {
	if x != nil {
		return x.LinksDeleted
	}
	return 0
}

func (x *DeleteDomainResponse) GetPagesDeleted() int32 {
	if x != nil {
		return x.PagesDeleted
	}
	return 0
}

type TriggerCrawlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerCrawlRequest) Reset() {
	*x = TriggerCrawlRequest{}
	mi := &file_crawler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerCrawlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerCrawlRequest) ProtoMessage() {}

func (x *TriggerCrawlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerCrawlRequest.ProtoReflect.Descriptor instead.
func (*TriggerCrawlRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{24}
}

func (x *TriggerCrawlRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CrawlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlResponse) Reset() {
	*x = CrawlResponse{}
	mi := &file_crawler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlResponse) ProtoMessage() {}

func (x *CrawlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlResponse.ProtoReflect.Descriptor instead.
func (*CrawlResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{25}
}

func (x *CrawlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CrawlResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_crawler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{26}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ChunkText     string                 `protobuf:"bytes,3,opt,name=chunk_text,json=chunkText,proto3" json:"chunk_text,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_crawler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{27}
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SearchResult) GetChunkText() string {
	if x != nil {
		return x.ChunkText
	}
	return ""
}

func (x *SearchResult) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SearchResult) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	ResultsCount  int32                  `protobuf:"varint,3,opt,name=results_count,json=resultsCount,proto3" json:"results_count,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	MetricsJson   string                 `protobuf:"bytes,5,opt,name=metrics_json,json=metricsJson,proto3" json:"metrics_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_crawler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_crawler_proto_rawDescGZIP(), []int{28}
}

func (x *SearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SearchResponse) GetResultsCount() int32 {
	if x != nil {
		return x.ResultsCount
	}
	return 0
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetMetricsJson() string {
	if x != nil {
		return x.MetricsJson
	}
	return ""
}

var File_crawler_proto protoreflect.FileDescriptor

const file_crawler_proto_rawDesc = "" +
	"\n" +
	"\rcrawler.proto\x12\acrawler\"\a\n" +
	"\x05Empty\"G\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x0fAddLinksRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"`\n" +
	"\x10AddLinksResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x05R\x05added\x12\x1e\n" +
	"\n" +
	"duplicated\x18\x02 \x01(\x05R\n" +
	"duplicated\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x05R\x06errors\"+\n" +
	"\x13ExtractLinksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"m\n" +
	"\x14ExtractLinksResponse\x12\x1c\n" +
	"\tprocessed\x18\x01 \x01(\x05R\tprocessed\x12\x1f\n" +
	"\vlinks_added\x18\x02 \x01(\x05R\n" +
	"linksAdded\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x05R\x06errors\"*\n" +
	"\x16CrawlSinglePageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"c\n" +
	"\x17CrawlSinglePageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"%\n" +
	"\x11DeleteLinkRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xa0\x01\n" +
	"\bLinkItem\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"T\n" +
	"\x10ListLinksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"R\n" +
	"\x11ListLinksResponse\x12'\n" +
	"\x05links\x18\x01 \x03(\v2\x11.crawler.LinkItemR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8f\x01\n" +
	"\x13LinksStatusResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x18\n" +
	"\apending\x18\x02 \x01(\x05R\apending\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\x05R\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\x05R\x05error\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\x05R\ablocked\"\x88\x01\n" +
	"\x0eLinkDomainStat\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x18\n" +
	"\apending\x18\x03 \x01(\x05R\apending\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\x05R\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\x05R\x05error\"J\n" +
	"\x15LinksByDomainResponse\x121\n" +
	"\adomains\x18\x01 \x03(\v2\x17.crawler.LinkDomainStatR\adomains\"<\n" +
	"\x10ListPagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\"\\\n" +
	"\x18ListPagesByDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\x05R\x04skip\"\xb6\x01\n" +
	"\vPageSummary\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"word_count\x18\x05 \x01(\x05R\twordCount\x12\x1d\n" +
	"\n" +
	"crawled_at\x18\x06 \x01(\tR\tcrawledAt\"?\n" +
	"\x11ListPagesResponse\x12*\n" +
	"\x05pages\x18\x01 \x03(\v2\x14.crawler.PageSummaryR\x05pages\"\"\n" +
	"\x0eGetPageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x80\x03\n" +
	"\x12PageDetailResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\ftext_content\x18\x04 \x01(\tR\vtextContent\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"word_count\x18\x06 \x01(\x05R\twordCount\x12\x1a\n" +
	"\bkeywords\x18\a \x03(\tR\bkeywords\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"crawled_at\x18\n" +
	" \x01(\tR\tcrawledAt\x12)\n" +
	"\x10embedding_status\x18\v \x01(\tR\x0fembeddingStatus\x12!\n" +
	"\fchunks_count\x18\f \x01(\x05R\vchunksCount\"'\n" +
	"\rDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\x80\x02\n" +
	"\x13DomainStatsResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1f\n" +
	"\vtotal_links\x18\x02 \x01(\x05R\n" +
	"totalLinks\x12.\n" +
	"\x13total_pages_crawled\x18\x03 \x01(\x05R\x11totalPagesCrawled\x12\x18\n" +
	"\apending\x18\x04 \x01(\x05R\apending\x12\x1c\n" +
	"\textracted\x18\x05 \x01(\x05R\textracted\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\x05R\asuccess\x12\x14\n" +
	"\x05error\x18\a \x01(\x05R\x05error\x12\x18\n" +
	"\ablocked\x18\b \x01(\x05R\ablocked\"`\n" +
	"\x14DeleteDomainResponse\x12#\n" +
	"\rlinks_deleted\x18\x01 \x01(\x05R\flinksDeleted\x12#\n" +
	"\rpages_deleted\x18\x02 \x01(\x05R\fpagesDeleted\"+\n" +
	"\x13TriggerCrawlRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"G\n" +
	"\rCrawlResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"S\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"\x99\x01\n" +
	"\fSearchResult\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"chunk_text\x18\x03 \x01(\tR\tchunkText\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x05 \x01(\x05R\vtotalChunks\"\x94\x01\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12#\n" +
	"\rresults_count\x18\x03 \x01(\x05R\fresultsCount\x12/\n" +
	"\aresults\x18\x04 \x03(\v2\x15.crawler.SearchResultR\aresults2\xb4\a\n" +
	"\fAdminService\x12?\n" +
	"\bAddLinks\x12\x18.crawler.AddLinksRequest\x1a\x19.crawler.AddLinksResponse\x12K\n" +
	"\fExtractLinks\x12\x1c.crawler.ExtractLinksRequest\x1a\x1d.crawler.ExtractLinksResponse\x12T\n" +
	"\x0fCrawlSinglePage\x12\x1f.crawler.CrawlSinglePageRequest\x1a .crawler.CrawlSinglePageResponse\x12>\n" +
	"\x0eGetLinksStatus\x12\x0e.crawler.Empty\x1a\x1c.crawler.LinksStatusResponse\x12H\n" +
	"\x16GetLinksStatusByDomain\x12\x0e.crawler.Empty\x1a\x1e.crawler.LinksByDomainResponse\x12B\n" +
	"\tListLinks\x12\x19.crawler.ListLinksRequest\x1a\x1a.crawler.ListLinksResponse\x12D\n" +
	"\n" +
	"DeleteLink\x12\x1a.crawler.DeleteLinkRequest\x1a\x1a.crawler.OperationResponse\x12B\n" +
	"\tListPages\x12\x19.crawler.ListPagesRequest\x1a\x1a.crawler.ListPagesResponse\x12R\n" +
	"\x11ListPagesByDomain\x12!.crawler.ListPagesByDomainRequest\x1a\x1a.crawler.ListPagesResponse\x12?\n" +
	"\aGetPage\x12\x17.crawler.GetPageRequest\x1a\x1b.crawler.PageDetailResponse\x12F\n" +
	"\x0eGetDomainStats\x12\x16.crawler.DomainRequest\x1a\x1c.crawler.DomainStatsResponse\x12E\n" +
	"\fDeleteDomain\x12\x16.crawler.DomainRequest\x1a\x1d.crawler.DeleteDomainResponse\x12D\n" +
	"\fTriggerCrawl\x12\x1c.crawler.TriggerCrawlRequest\x1a\x16.crawler.CrawlResponse2J\n" +
	"\rSearchService\x129\n" +
	"\x06Search\x12\x16.crawler.SearchRequest\x1a\x17.crawler.SearchResponseB\x1dZ\x1bbackend/internal/grpc/protob\x06proto3"

var (
	file_crawler_proto_rawDescOnce sync.Once
	file_crawler_proto_rawDescData []byte
)

func file_crawler_proto_rawDescGZIP() []byte {
	file_crawler_proto_rawDescOnce.Do(func() {
		file_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crawler_proto_rawDesc), len(file_crawler_proto_rawDesc)))
	})
	return file_crawler_proto_rawDescData
}

var file_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_crawler_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: crawler.Empty
	(*OperationResponse)(nil),        // 1: crawler.OperationResponse
	(*AddLinksRequest)(nil),          // 2: crawler.AddLinksRequest
	(*AddLinksResponse)(nil),         // 3: crawler.AddLinksResponse
	(*ExtractLinksRequest)(nil),      // 4: crawler.ExtractLinksRequest
	(*ExtractLinksResponse)(nil),     // 5: crawler.ExtractLinksResponse
	(*CrawlSinglePageRequest)(nil),   // 6: crawler.CrawlSinglePageRequest
	(*CrawlSinglePageResponse)(nil),  // 7: crawler.CrawlSinglePageResponse
	(*DeleteLinkRequest)(nil),        // 8: crawler.DeleteLinkRequest
	(*LinkItem)(nil),                 // 9: crawler.LinkItem
	(*ListLinksRequest)(nil),         // 10: crawler.ListLinksRequest
	(*ListLinksResponse)(nil),        // 11: crawler.ListLinksResponse
	(*LinksStatusResponse)(nil),      // 12: crawler.LinksStatusResponse
	(*LinkDomainStat)(nil),           // 13: crawler.LinkDomainStat
	(*LinksByDomainResponse)(nil),    // 14: crawler.LinksByDomainResponse
	(*ListPagesRequest)(nil),         // 15: crawler.ListPagesRequest
	(*ListPagesByDomainRequest)(nil), // 16: crawler.ListPagesByDomainRequest
	(*PageSummary)(nil),              // 17: crawler.PageSummary
	(*ListPagesResponse)(nil),        // 18: crawler.ListPagesResponse
	(*GetPageRequest)(nil),           // 19: crawler.GetPageRequest
	(*PageDetailResponse)(nil),       // 20: crawler.PageDetailResponse
	(*DomainRequest)(nil),            // 21: crawler.DomainRequest
	(*DomainStatsResponse)(nil),      // 22: crawler.DomainStatsResponse
	(*DeleteDomainResponse)(nil),     // 23: crawler.DeleteDomainResponse
	(*TriggerCrawlRequest)(nil),      // 24: crawler.TriggerCrawlRequest
	(*CrawlResponse)(nil),            // 25: crawler.CrawlResponse
	(*SearchRequest)(nil),            // 26: crawler.SearchRequest
	(*SearchResult)(nil),             // 27: crawler.SearchResult
	(*SearchResponse)(nil),           // 28: crawler.SearchResponse
}
var file_crawler_proto_depIdxs = []int32{
	9,  // 0: crawler.ListLinksResponse.links:type_name -> crawler.LinkItem
	13, // 1: crawler.LinksByDomainResponse.domains:type_name -> crawler.LinkDomainStat
	17, // 2: crawler.ListPagesResponse.pages:type_name -> crawler.PageSummary
	27, // 3: crawler.SearchResponse.results:type_name -> crawler.SearchResult
	2,  // 4: crawler.AdminService.AddLinks:input_type -> crawler.AddLinksRequest
	4,  // 5: crawler.AdminService.ExtractLinks:input_type -> crawler.ExtractLinksRequest
	6,  // 6: crawler.AdminService.CrawlSinglePage:input_type -> crawler.CrawlSinglePageRequest
	0,  // 7: crawler.AdminService.GetLinksStatus:input_type -> crawler.Empty
	0,  // 8: crawler.AdminService.GetLinksStatusByDomain:input_type -> crawler.Empty
	10, // 9: crawler.AdminService.ListLinks:input_type -> crawler.ListLinksRequest
	8,  // 10: crawler.AdminService.DeleteLink:input_type -> crawler.DeleteLinkRequest
	15, // 11: crawler.AdminService.ListPages:input_type -> crawler.ListPagesRequest
	16, // 12: crawler.AdminService.ListPagesByDomain:input_type -> crawler.ListPagesByDomainRequest
	19, // 13: crawler.AdminService.GetPage:input_type -> crawler.GetPageRequest
	21, // 14: crawler.AdminService.GetDomainStats:input_type -> crawler.DomainRequest
	21, // 15: crawler.AdminService.DeleteDomain:input_type -> crawler.DomainRequest
	24, // 16: crawler.AdminService.TriggerCrawl:input_type -> crawler.TriggerCrawlRequest
	26, // 17: crawler.SearchService.Search:input_type -> crawler.SearchRequest
	3,  // 18: crawler.AdminService.AddLinks:output_type -> crawler.AddLinksResponse
	5,  // 19: crawler.AdminService.ExtractLinks:output_type -> crawler.ExtractLinksResponse
	7,  // 20: crawler.AdminService.CrawlSinglePage:output_type -> crawler.CrawlSinglePageResponse
	12, // 21: crawler.AdminService.GetLinksStatus:output_type -> crawler.LinksStatusResponse
	14, // 22: crawler.AdminService.GetLinksStatusByDomain:output_type -> crawler.LinksByDomainResponse
	11, // 23: crawler.AdminService.ListLinks:output_type -> crawler.ListLinksResponse
	1,  // 24: crawler.AdminService.DeleteLink:output_type -> crawler.OperationResponse
	18, // 25: crawler.AdminService.ListPages:output_type -> crawler.ListPagesResponse
	18, // 26: crawler.AdminService.ListPagesByDomain:output_type -> crawler.ListPagesResponse
	20, // 27: crawler.AdminService.GetPage:output_type -> crawler.PageDetailResponse
	22, // 28: crawler.AdminService.GetDomainStats:output_type -> crawler.DomainStatsResponse
	23, // 29: crawler.AdminService.DeleteDomain:output_type -> crawler.DeleteDomainResponse
	25, // 30: crawler.AdminService.TriggerCrawl:output_type -> crawler.CrawlResponse
	28, // 31: crawler.SearchService.Search:output_type -> crawler.SearchResponse
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_crawler_proto_init() }
func file_crawler_proto_init() {
	if File_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crawler_proto_rawDesc), len(file_crawler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_crawler_proto_goTypes,
		DependencyIndexes: file_crawler_proto_depIdxs,
		MessageInfos:      file_crawler_proto_msgTypes,
	}.Build()
	File_crawler_proto = out.File
	file_crawler_proto_goTypes = nil
	file_crawler_proto_depIdxs = nil
}
